--Dependancies
local TweenService = game:GetService("TweenService")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local InterfaceUtils = require(ReplicatedStorage.Shared.Utilities.InterfaceUtils)

--Configuration
local HOVER_SCALE = 1.05
local ANIMATION_SPEED = 0.1

--Observer function
return function(Element: GuiObject)
	local OriginalSize = Element.Size
	local SizeOnHover = InterfaceUtils.MultiplyUdim2(OriginalSize, HOVER_SCALE)
	local HoverTween = TweenService:Create(Element, TweenInfo.new(ANIMATION_SPEED), {Size = SizeOnHover})
	local RestoreTween = TweenService:Create(Element, TweenInfo.new(ANIMATION_SPEED), {Size = OriginalSize})
	local HoverConnection = Element.MouseEnter:Connect(function() HoverTween:Play() end)
	local LeaveConnection = Element.MouseLeave:Connect(function() RestoreTween:Play() end)
	return function()
		Element.Size = OriginalSize
		HoverTween:Destroy()
		RestoreTween:Destroy()
		HoverConnection:Disconnect()
		LeaveConnection:Disconnect()
	end
end